# Generated by Django 4.2 on 2023-04-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_Husbandry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Animal_Husbandry',
                'verbose_name_plural': 'Animal_Husbandrys',
            },
        ),
        migrations.CreateModel(
            name='Crop_Diseases_and_Protections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Crop_Diseases_and_Protection',
                'verbose_name_plural': 'Crop_Diseases_and_Protections',
            },
        ),
        migrations.CreateModel(
            name='Economic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Economic',
                'verbose_name_plural': 'Economics',
            },
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Government',
                'verbose_name_plural': 'Governments',
            },
        ),
        migrations.CreateModel(
            name='International',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'International',
                'verbose_name_plural': 'Internationals',
            },
        ),
        migrations.CreateModel(
            name='Negative_sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Negative_sentiment',
                'verbose_name_plural': 'Negative_sentiments',
            },
        ),
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'NewsArticle',
                'verbose_name_plural': 'NewsArticles',
            },
        ),
        migrations.CreateModel(
            name='Not_Time_sensitive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Not_Time_sensitive',
                'verbose_name_plural': 'Not_Time_sensitives',
            },
        ),
        migrations.CreateModel(
            name='OtherAgriNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'OtherAgriNew',
                'verbose_name_plural': 'OtherAgriNews',
            },
        ),
        migrations.CreateModel(
            name='Positive_sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Positive_sentiment',
                'verbose_name_plural': 'Positive_sentiments',
            },
        ),
        migrations.CreateModel(
            name='Technologies_and_Methods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Technologies_and_Method',
                'verbose_name_plural': 'Technologies_and_Methods',
            },
        ),
        migrations.CreateModel(
            name='Time_sensitive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Time_sensitive',
                'verbose_name_plural': 'Time_sensitives',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Weather',
                'verbose_name_plural': 'Weathers',
            },
        ),
    ]
