# Generated by Django 4.2 on 2023-04-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='government',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticles',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
